### PR TITLE
anndata 0.8 compat

### PR DESCRIPTION
**Pull request by ivirshup**
This is a draft PR which aiming to make mudata compatible with anndata 0.8. Ideally it will also be compatible with 0.7 and will have as few changes as possible.

### CODE REVIEW

**Comment by ivirshup** [comment]
lol, maybe point me at a trivial change to make so I can get CI here

**Comment by ivirshup** [comment]
Some of the stuff from #7 is going to get broken by https://github.com/theislab/anndata/pull/554, which I think I'll merge tomorrow. Hopefully no release has been made? I think it'd make sense to only release with that once the next anndata release is out.

**Comment by gtca** [comment]
Thanks for the heads-up, I expect we'll have `0.1.2` (`0.2.0`?) with `anndata >=0.8` then.

**Comment by gtca** [comment]
@ivirshup Seems to work now, both with HDF5 and Zarr. In case you might want to take a look there are no glaring omissions.

**Review by ilia-kats — APPROVED** [review]
LGTM

**Pull request merged**
